import { Feed } from './supabase';

export const mockFeeds: Feed[] = [
  {
    id: 'mock-1',
    title: 'AI Revolution in Financial Markets: What Investors Need to Know',
    summary: 'Artificial intelligence is transforming how markets operate, from algorithmic trading to risk assessment. Here\'s what the latest developments mean for your portfolio.',
    content: 'The integration of AI in financial markets has reached unprecedented levels...',
    avatar_type: 'robot',
    category: 'Technology',
    created_at: new Date().toISOString(),
    published_at: new Date().toISOString().split('T')[0],
  },
  {
    id: 'mock-2',
    title: 'Sustainable Investing Gains Momentum in 2026',
    summary: 'ESG-focused funds continue to outperform traditional investments as more companies commit to carbon neutrality targets.',
    content: 'Environmental, social, and governance factors are becoming central to investment decisions...',
    avatar_type: 'ai',
    category: 'Finance',
    created_at: new Date().toISOString(),
    published_at: new Date().toISOString().split('T')[0],
  },
  {
    id: 'mock-3',
    title: 'Central Banks Navigate Inflation Challenges',
    summary: 'Global monetary policy remains in focus as central banks balance growth objectives with price stability concerns.',
    content: 'The delicate balance between stimulating economic growth and controlling inflation...',
    avatar_type: 'brain',
    category: 'Economy',
    created_at: new Date().toISOString(),
    published_at: new Date().toISOString().split('T')[0],
  },
  {
    id: 'mock-4',
    title: 'Emerging Markets Show Strong Recovery Signs',
    summary: 'After years of volatility, emerging market equities are attracting renewed investor interest with promising growth indicators.',
    content: 'Emerging markets are experiencing a renaissance as structural reforms take hold...',
    avatar_type: 'robot',
    category: 'Markets',
    created_at: new Date().toISOString(),
    published_at: new Date().toISOString().split('T')[0],
  },
  {
    id: 'mock-5',
    title: 'The Future of Digital Currencies in Global Trade',
    summary: 'Central bank digital currencies are reshaping international commerce and challenging traditional payment systems.',
    content: 'Digital currencies backed by central banks are gaining traction worldwide...',
    avatar_type: 'ai',
    category: 'Technology',
    created_at: new Date().toISOString(),
    published_at: new Date().toISOString().split('T')[0],
  },
];
